### ISSUE TITLE
Pylint compatibility

### ISSUE THREAD

**Issue by nbaju1** [statnett/quick-xmltodict#11]
Cool package!

Is there a way to make this compatible with linters like Pylint? From Pylint `No name 'parse' in module 'quick_xmltodict'`. I'm guessing this is due to the package being Rust backed?

**Comment by danhje** [comment]
Hi @nbaju1, thanks for the interest in the package.

I think the error stems from the fact that Pylint doesn't load C extensions by default, for security reasons. I tried running Pylint with `--extension-pkg-allow-list=quick_xmltodict`, and the error disappeared. If you don't want to have to pass this argument every time, you can apparently allow all C extensions through a config file. You could of course also just mute mute that specific error if you don't want the whole C extension to be analyzed. You can read more about those three options [here](https://pylint.readthedocs.io/en/latest/user_guide/messages/error/no-member.html) (I don't know why those tips aren't also found on the help page for the [no-name-in-module](https://pylint.readthedocs.io/en/stable/user_guide/messages/error/no-name-in-module.html) error you're getting).

Let me know if this doesn't work for you and you think there's something I can do that I've overlooked, that will make Pylint happy.
